### ISSUE TITLE
Doesn't work in moblie

### ISSUE THREAD

**Issue by aswooo** [AYUPuzzler/Puzzler#6]
아래의 이미지는 이전 이슈를 수정하고 발생한다.

![image](https://user-images.githubusercontent.com/86454635/137417038-e4ed9072-8c3f-48b2-bbea-07647ba43534.png)

유니티에서 실행을 했을 때엔 문제가 없지만 안드로이드로 빌드를 한 후에는 이미지가 렌더링 되지 않는 문제가 발생한다.

**Comment by leejimin3** [comment]
본 이슈는 쉐이더 적용법을 사용하여 해결하였음.
